-- Script để xóa sạch dữ liệu từ tất cả các bảng trong cơ sở dữ liệu Oracle
-- Lưu ý: Script này sẽ xóa TẤT CẢ dữ liệu từ các bảng, nhưng giữ nguyên cấu trúc bảng

-- Tắt tạm thời các ràng buộc khóa ngoại để tránh lỗi khi xóa dữ liệu
BEGIN
   FOR c IN (SELECT constraint_name, table_name FROM user_constraints WHERE constraint_type = 'R') LOOP
      BEGIN
         EXECUTE IMMEDIATE 'ALTER TABLE ' || c.table_name || ' DISABLE CONSTRAINT ' || c.constraint_name || ' WAIT 10';
      EXCEPTION
         WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Không thể vô hiệu hóa ràng buộc ' || c.constraint_name || ' trên bảng ' || c.table_name || ': ' || SQLERRM);
      END;
   END LOOP;
END;
/

-- Xóa dữ liệu từ các bảng con trước (bảng có khóa ngoại tham chiếu đến bảng khác)

-- Xóa dữ liệu từ các bảng liên quan đến đặt phòng và dịch vụ
DELETE FROM DICH_VU_YEU_CAU;
DELETE FROM KHOA_PHONG;
DELETE FROM DICH_VU_MAC_DINH;
DELETE FROM HOA_DON;
DELETE FROM CHI_TIET_DAT_PHONG;
DELETE FROM DAT_PHONG;
DELETE FROM THOIGIAN_PHONG_BAN;
DELETE FROM KHO_MA_GIAM_GIA;
DELETE FROM DOI_DIEM;
DELETE FROM GIAMGIA;
DELETE FROM GOI_DAT_PHONG;
DELETE FROM DICH_VU_KHU_NGHI_DUONG;
DELETE FROM DICH_VU;

-- Xóa dữ liệu từ các bảng liên quan đến phòng và tiện ích
DELETE FROM TIEN_ICH_PHONG;
DELETE FROM TIEN_ICH;
DELETE FROM PHONG;
DELETE FROM HINH_PHONG;
DELETE FROM LOAI_PHONG;

-- Xóa dữ liệu từ các bảng liên quan đến khu nghỉ dưỡng
DELETE FROM DANH_GIA;
DELETE FROM HINH_KHU_NGHI_DUONG;
DELETE FROM KHU_NGHI_DUONG;

-- Xóa dữ liệu từ các bảng liên quan đến địa chỉ
DELETE FROM PHUONG;
DELETE FROM QUAN;
DELETE FROM THANH_PHO;

-- Xóa dữ liệu từ các bảng liên quan đến đối tác và khách hàng
DELETE FROM LICH_SU_RUT_TIEN;
DELETE FROM DOI_TAC;
DELETE FROM KHACH_HANG;

-- Xóa dữ liệu từ các bảng liên quan đến tài khoản và phân quyền
DELETE FROM ACCOUNT_ASSIGN_ROLE;
DELETE FROM ACCOUNT_ROLE_GROUP;
DELETE FROM ASSIGN_ROLE_GROUP;
DELETE FROM ACCOUNT_TOKEN;
DELETE FROM TAI_KHOAN;
DELETE FROM ROLE;
DELETE FROM ROLE_GROUP;
DELETE FROM FUNCTION;
DELETE FROM NGUOI_DUNG;

-- Bật lại các ràng buộc khóa ngoại
BEGIN
   FOR c IN (SELECT constraint_name, table_name FROM user_constraints WHERE constraint_type = 'R') LOOP
      BEGIN
         EXECUTE IMMEDIATE 'ALTER TABLE ' || c.table_name || ' ENABLE CONSTRAINT ' || c.constraint_name || ' WAIT 10';
      EXCEPTION
         WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Không thể kích hoạt lại ràng buộc ' || c.constraint_name || ' trên bảng ' || c.table_name || ': ' || SQLERRM);
      END;
   END LOOP;
END;
/

-- Đặt lại các sequence (auto increment) về 1
BEGIN
   -- Đặt lại các sequence cho các cột identity
   FOR tab_rec IN (SELECT table_name, column_name
                  FROM user_tab_columns
                  WHERE identity_column = 'YES') LOOP
      -- Sử dụng ALTER TABLE ... MODIFY ... để đặt lại giá trị identity
      BEGIN
         EXECUTE IMMEDIATE 'ALTER TABLE ' || tab_rec.table_name ||
                          ' MODIFY ' || tab_rec.column_name ||
                          ' GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)';
      EXCEPTION
         WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Không thể đặt lại identity cho bảng ' || tab_rec.table_name || ': ' || SQLERRM);
      END;
   END LOOP;

   -- Đặt lại các sequence thường (không phải system-generated)
   FOR seq_rec IN (SELECT sequence_name FROM user_sequences WHERE sequence_name NOT LIKE 'ISEQ$$%') LOOP
      BEGIN
         EXECUTE IMMEDIATE 'DROP SEQUENCE ' || seq_rec.sequence_name;
      EXCEPTION
         WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Không thể xóa sequence ' || seq_rec.sequence_name || ': ' || SQLERRM);
      END;
   END LOOP;
END;
/

-- Commit các thay đổi
COMMIT;

-- Hiển thị thông báo hoàn thành
SELECT 'Đã xóa sạch dữ liệu và đặt lại auto increment về 1 cho tất cả các bảng' AS "Thông báo" FROM DUAL;
