INSERT INTO "FUNCTION"(FUNCTION_NAME) VALUES('VIEW_ROOM_LIST');
INSERT INTO "FUNCTION"(FUNCTION_NAME) VALUES('PARTNER_VIEW');
INSERT INTO "FUNCTION"(FUNCTION_NAME) VALUES('CUSTOMER_VIEW');
INSERT INTO "FUNCTION"(FUNCTION_NAME) VALUES('ADMIN_VIEW');
COMMIT;

SELECT * FROM LOAI_PHONG lp;

INSERT INTO ROLE_GROUP(GROUP_NAME, DESCRIPTION) VALUES ('ADMIN', '');
INSERT INTO ROLE_GROUP(GROUP_NAME, DESCRIPTION) VALUES ('PARTNER', '');
INSERT INTO ROLE_GROUP(GROUP_NAME, DESCRIPTION) VALUES ('CUSTOMER', '');
COMMIT;
SELECT * FROM ROLE_GROUP rg;

INSERT INTO ROLE(FUNCTION_ID, ADD_PERM, EDIT_PERM, DELETE_PERM, DOWNLOAD_PERM, VIEW_PERM)
VALUES (1,1,1,1,1,1);
INSERT INTO ROLE(FUNCTION_ID, ADD_PERM, EDIT_PERM, DELETE_PERM, DOWNLOAD_PERM, VIEW_PERM)
VALUES (2,1,1,1,1,1);
INSERT INTO ROLE(FUNCTION_ID, ADD_PERM, EDIT_PERM, DELETE_PERM, DOWNLOAD_PERM, VIEW_PERM)
VALUES (3,1,1,1,1,1);
INSERT INTO ROLE(FUNCTION_ID, ADD_PERM, EDIT_PERM, DELETE_PERM, DOWNLOAD_PERM, VIEW_PERM)
VALUES (4,1,1,1,1,1);
COMMIT;
SELECT * FROM ROLE;

INSERT INTO NGUOI_DUNG(HO_TEN, EMAIL, SDT, CCCD)
VALUES ('Nguyen Thanh Thang', '23521427@gm.uit.edu.vn', '1234567890', '082205111175');
INSERT INTO NGUOI_DUNG(HO_TEN, EMAIL, SDT, CCCD)
VALUES ('Tran Nam Phong', '23521172@gm.uit.edu.vn', '1234567890', '123456678900');
INSERT INTO NGUOI_DUNG(HO_TEN, EMAIL, SDT, CCCD)
VALUES ('To Tran Nha Uyen', '23521765@gm.uit.edu.vn', '1234567890', '123456678900');
INSERT INTO NGUOI_DUNG(HO_TEN, EMAIL, SDT, CCCD)
VALUES ('Le Dao Anh Thu', '23521537@gm.uit.edu.vn', '1234567890', '123456678900');
COMMIT;
SELECT * FROM NGUOI_DUNG;

INSERT INTO TAI_KHOAN(USER_ID, TEN_TAI_KHOAN, MAT_KHAU)
VALUES (2, 'ThanhThang123', 'hash-pass-of-123');
INSERT INTO TAI_KHOAN(USER_ID, TEN_TAI_KHOAN, MAT_KHAU)
VALUES (3, 'NamPhong123', 'hash-pass-of-123');
INSERT INTO TAI_KHOAN(USER_ID, TEN_TAI_KHOAN, MAT_KHAU)
VALUES (4, 'NhaUyen123', 'hash-pass-of-123');
INSERT INTO TAI_KHOAN(USER_ID, TEN_TAI_KHOAN, MAT_KHAU)
VALUES (5, 'AnhThu123', 'hash-pass-of-123');
COMMIT;
SELECT * FROM TAI_KHOAN;

INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (1,1);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (1,2);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (1,3);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (2,1);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (2,2);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (2,3);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (3,1);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (3,2);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (3,3);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (4,1);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (4,2);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (4,3);
COMMIT;
SELECT * FROM ACCOUNT_ROLE_GROUP;

INSERT INTO ASSIGN_ROLE_GROUP(ROLE_GROUP_ID, ROLE_ID) VALUES (1,4);
INSERT INTO ASSIGN_ROLE_GROUP(ROLE_GROUP_ID, ROLE_ID) VALUES (2,3);
INSERT INTO ASSIGN_ROLE_GROUP(ROLE_GROUP_ID, ROLE_ID) VALUES (3,2);
COMMIT;
SELECT * FROM ASSIGN_ROLE_GROUP arg;

INSERT INTO ACCOUNT_ASSIGN_ROLE(ACCOUNT_ID,ROLE_ID) VALUES(2,1);
COMMIT;
SELECT * FROM ACCOUNT_ASSIGN_ROLE;


 UPDATE TAI_KHOAN
 SET MAT_KHAU = 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3'
 WHERE MAT_KHAU = 'hash-pass-of-123';

SELECT * FROM TAI_KHOAN tk;
COMMIT;

SELECT * FROM ACCOUNT_ROLE_GROUP arg;


SELECT * FROM THANH_PHO tp;
INSERT INTO THANH_PHO (TEN_THANH_PHO) VALUES ('H? Ch� Minh');
INSERT INTO THANH_PHO (TEN_THANH_PHO) VALUES ('H� N?i');
INSERT INTO THANH_PHO (TEN_THANH_PHO) VALUES ('L�m �?ng');
INSERT INTO THANH_PHO (TEN_THANH_PHO) VALUES ('B� R?a - Vung T�u');
COMMIT;

INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (1,'Qu?n 1');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (1,'Qu?n 2');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (1,'Qu?n 3');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (1,'Qu?n 4');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (2,'Ba ��nh');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (2,'C?u Gi?y');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (2,'Ho�n Ki?m');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (2,'H� ��ng');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (3,'�� L?t');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (4,'Vung T�u');
COMMIT;
SELECT * FROM QUAN q;


INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (1,'B?n Th�nh');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (1,'C?u �ng L�nh');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (1,'C� Giang');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (2,'Th?o �i?n');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (2,'Th? Thi�m');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (2,'An Kh�nh');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (3,'Phu?ng 1');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (3,'Phu?ng 2');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (3,'Phu?ng 3');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (4,'Phu?ng 1');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (4,'Phu?ng 2');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (4,'Phu?ng 3');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (5,'Vinh Ph�c');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (6,'D?ch V?ng');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (7,'�?ng Xu�n');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (8,'La Kh�');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (9,'�?ng Xu�n');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (10,'Phu?ng 1');
COMMIT;
SELECT * FROM PHUONG;

SELECT * FROM KHU_NGHI_DUONG knd;
COMMIT;

EXEC ThemKhuNghiDuong('ThanhThang123_2025-04-02_20:23:45','Resort name 2', '23 Ho�ng Van Th?', 'H? Ch� Minh', 'Qu?n 1', 'B?n Th�nh');

SELECT * FROM KHU_NGHI_DUONG knd;
SELECT * FROM ACCOUNT_TOKEN at;
SELECT * FROM TAI_KHOAN tk;
INSERT INTO DOI_TAC(ID_TAI_KHOAN, DIA_CHI, TAIKHOAN_NGANHANG, TEN_TKNH, TEN_NGANHANG, TINH_TRANG)
VALUES (1, 'KTX KHU A', '0348489748', 'NGUYEN THANH THANG', 'MBBANK', 'ACTIVE');
COMMIT;

SELECT * FROM DOI_TAC dt;


SELECT * FROM NLS_DATABASE_PARAMETERS WHERE PARAMETER = 'NLS_CHARACTERSET';

UPDATE THANH_PHO
SET TEN_THANH_PHO = 'Ho Chi Minh'
WHERE TEN_THANH_PHO = 'H? Ch� Minh';

UPDATE THANH_PHO
SET TEN_THANH_PHO = 'H? Ch� Minh'
WHERE TEN_THANH_PHO = 'Ho Chi Minh';

SELECT * FROM THANH_PHO tp;

SELECT * FROM LOAI_PHONG lp;
SELECT * FROM KHU_NGHI_DUONG knd;
SELECT * FROM DOI_TAC dt;
INSERT INTO LOAI_PHONG(ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (5, 'Ph�ng H?ng Sang View Bi?n', 20.00, 'Ph�ng ��i', 'H?ng sang', 1, 2, 1000000);
INSERT INTO LOAI_PHONG(ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (6, 'Ph�ng H?ng Sang View Ph?', 20.00, 'Ph�ng ��i', 'H?ng sang', 1, 2, 1000000);
COMMIT;



ALTER TABLE KHU_NGHI_DUONG MODIFY (DANH_GIA NULL);

SELECT * FROM KHU_NGHI_DUONG