
-- 4. Insert Người dùng
INSERT INTO NGUOI_DUNG (HO_TEN, EMAIL, SDT, CCCD)
VALUES ( 'Nguyễn Văn A', 'partnerA@example.com', '0912345678', '012345678901');
INSERT INTO NGUOI_DUNG (HO_TEN, EMAIL, SDT, CCCD)
VALUES ('Nguyễn Văn B', 'jjhkA@example.com', '0912345678', '012345678901');

INSERT INTO NGUOI_DUNG (HO_TEN, EMAIL, SDT, CCCD)
VALUES ('Trần Nam Phong', 'chayTheoConChoTuongDoLaEm1993@yahoo.com', '0901234567', '079123456789');
INSERT INTO NGUOI_DUNG ( HO_TEN, EMAIL, SDT, CCCD)
VALUES('Đặng Nam Phong', 'Sieutromtheki20@yahoo.com', '0912345678', '079234567890');
INSERT INTO NGUOI_DUNG ( HO_TEN, EMAIL, SDT, CCCD)
VALUES('Lê Nam Phong', 'Khunglongbaochua_tapmuabale2793@yahoo.com', '0923456789', '079345678901');
INSERT INTO NGUOI_DUNG ( HO_TEN, EMAIL, SDT, CCCD)
VALUES('Phạm Nam Phong', 'Khongyeu_congai_nhagiau@yahoo.com', '0934567890', '079456789012');
INSERT INTO NGUOI_DUNG ( HO_TEN, EMAIL, SDT, CCCD)
VALUES('Dương Nam Phong', 'Batnapquantai_honemlancuoi1995', '0945678901', '079567890123');


-- 5. Insert Tài khoản
INSERT INTO TAI_KHOAN ( USER_ID, TEN_TAI_KHOAN, MAT_KHAU)
VALUES ( 1, 'partnerA', 'password123');
INSERT INTO TAI_KHOAN ( USER_ID, TEN_TAI_KHOAN, MAT_KHAU)
VALUES ( 2, 'KhacHangB', 'password123');
INSERT INTO TAI_KHOAN ( USER_ID, TEN_TAI_KHOAN, MAT_KHAU)
VALUES ( 3, 'KhacHangC', 'password123');
INSERT INTO TAI_KHOAN ( USER_ID, TEN_TAI_KHOAN, MAT_KHAU)
VALUES ( 4, 'KhacHangD', 'password123');
INSERT INTO TAI_KHOAN ( USER_ID, TEN_TAI_KHOAN, MAT_KHAU)
VALUES ( 5, 'KhacHangE', 'password123');
INSERT INTO TAI_KHOAN ( USER_ID, TEN_TAI_KHOAN, MAT_KHAU)
VALUES ( 6, 'KhacHangF', 'password123');
INSERT INTO TAI_KHOAN ( USER_ID, TEN_TAI_KHOAN, MAT_KHAU)
VALUES ( 7, 'KhacHangG', 'password123');

-- 6. Insert Đối tác
INSERT INTO DOI_TAC (ID_TAI_KHOAN, DIA_CHI, TAIKHOAN_NGANHANG, TEN_TKNH, TEN_NGANHANG, TINH_TRANG)
VALUES ( 1, '123 Đường ABC, Quận 1', '123456789', 'Nguyễn Văn A', 'Vietcombank', 'ACTIVE');
INSERT INTO DOI_TAC (ID_TAI_KHOAN, DIA_CHI, TAIKHOAN_NGANHANG, TEN_TKNH, TEN_NGANHANG, TINH_TRANG)
VALUES ( 7, '123 Đường ABC, Quận 1', '123456789', 'Nguyễn Văn B', 'Vietcombank', 'ACTIVE');

-- Insert khách hàng
INSERT INTO KHACH_HANG(ID_TAI_KHOAN, DIA_CHI, DIEM_TICH_LUY, TINH_TRANG)
VALUES(2,'Vietnam',300, 'ACTIVE');
INSERT INTO KHACH_HANG( ID_TAI_KHOAN, DIA_CHI, DIEM_TICH_LUY, TINH_TRANG)
VALUES(3,'Vietnam',300, 'ACTIVE');
INSERT INTO KHACH_HANG( ID_TAI_KHOAN, DIA_CHI, DIEM_TICH_LUY, TINH_TRANG)
VALUES(4,'Vietnam',300, 'ACTIVE');
INSERT INTO KHACH_HANG( ID_TAI_KHOAN, DIA_CHI, DIEM_TICH_LUY, TINH_TRANG)
VALUES(5,'Vietnam',300, 'ACTIVE');
INSERT INTO KHACH_HANG( ID_TAI_KHOAN, DIA_CHI, DIEM_TICH_LUY, TINH_TRANG)
VALUES(6,'Vietnam',300, 'ACTIVE');
-----------------------------
-- Insert Thành phố
INSERT INTO THANH_PHO (ID, TEN_THANH_PHO) VALUES (1, 'TP.HCM');

-- Insert Quận
INSERT INTO QUAN (ID, ID_THANH_PHO, TEN_QUAN) VALUES (1, 1, 'Quận 1');
INSERT INTO QUAN (ID, ID_THANH_PHO, TEN_QUAN) VALUES (2, 1, 'Quận 3');
INSERT INTO QUAN (ID, ID_THANH_PHO, TEN_QUAN) VALUES (3, 1, 'Quận 5');

-- Insert Phường
INSERT INTO PHUONG (ID, ID_QUAN, TEN_PHUONG) VALUES (1, 1, 'Phường Bến Nghé');
INSERT INTO PHUONG (ID, ID_QUAN, TEN_PHUONG) VALUES (2, 1, 'Phường Đa Kao');
INSERT INTO PHUONG (ID, ID_QUAN, TEN_PHUONG) VALUES (3, 2, 'Phường 7');
INSERT INTO PHUONG (ID, ID_QUAN, TEN_PHUONG) VALUES (4, 2, 'Phường 9');
INSERT INTO PHUONG (ID, ID_QUAN, TEN_PHUONG) VALUES (5, 3, 'Phường 10');
INSERT INTO PHUONG (ID, ID_QUAN, TEN_PHUONG) VALUES (6, 3, 'Phường 12');

ALTER TABLE KHU_NGHI_DUONG MODIFY (DANH_GIA NULL);
ALTER TABLE KHU_NGHI_DUONG MODIFY (MO_TA NULL);
ALTER TABLE KHU_NGHI_DUONG MODIFY (IMG_360_URL NULL);

-- Insert Khu nghỉ dưỡng
INSERT INTO KHU_NGHI_DUONG (ID, ID_DOI_TAC, TEN, DIA_CHI, PHUONG_ID, DANH_GIA) VALUES (1, 1, 'Sunshine Resort', '12 Nguyễn Huệ', 1, 5);
INSERT INTO KHU_NGHI_DUONG (ID, ID_DOI_TAC, TEN, DIA_CHI, PHUONG_ID, DANH_GIA) VALUES (2, 1, 'Emerald Bay Resort', '24 Lê Lợi', 1, 4);
INSERT INTO KHU_NGHI_DUONG (ID, ID_DOI_TAC, TEN, DIA_CHI, PHUONG_ID, DANH_GIA) VALUES (3, 1, 'Golden Sands Resort', '78 Pasteur', 2, 4);
INSERT INTO KHU_NGHI_DUONG (ID, ID_DOI_TAC, TEN, DIA_CHI, PHUONG_ID, DANH_GIA) VALUES (4, 1, 'Green Valley Resort', '15 Trần Hưng Đạo', 2, 5);
INSERT INTO KHU_NGHI_DUONG (ID, ID_DOI_TAC, TEN, DIA_CHI, PHUONG_ID, DANH_GIA) VALUES (5, 1, 'White Pearl Resort', '89 Đồng Khởi', 1, 5);
INSERT INTO KHU_NGHI_DUONG (ID, ID_DOI_TAC, TEN, DIA_CHI, PHUONG_ID, DANH_GIA) VALUES (6, 1, 'Ocean Breeze Resort', '5 Nguyễn Đình Chiểu', 3, 5);
INSERT INTO KHU_NGHI_DUONG (ID, ID_DOI_TAC, TEN, DIA_CHI, PHUONG_ID, DANH_GIA) VALUES (7, 1, 'Blue Sky Resort', '10 Võ Văn Tần', 3, 4);
INSERT INTO KHU_NGHI_DUONG (ID, ID_DOI_TAC, TEN, DIA_CHI, PHUONG_ID, DANH_GIA) VALUES (8, 1, 'Ruby Island Resort', '19 Nguyễn Thượng Hiền', 4, 5);
INSERT INTO KHU_NGHI_DUONG (ID, ID_DOI_TAC, TEN, DIA_CHI, PHUONG_ID, DANH_GIA) VALUES (9, 1, 'White Lotus Resort', '45 Cao Thắng', 4, 4);
INSERT INTO KHU_NGHI_DUONG (ID, ID_DOI_TAC, TEN, DIA_CHI, PHUONG_ID, DANH_GIA) VALUES (10, 1, 'Silver Sea Resort', '11 Trần Quốc Thảo', 3, 5);
INSERT INTO KHU_NGHI_DUONG (ID, ID_DOI_TAC, TEN, DIA_CHI, PHUONG_ID, DANH_GIA) VALUES (11, 1, 'Diamond Shore Resort', '99 Nguyễn Trãi', 5, 5);
INSERT INTO KHU_NGHI_DUONG (ID, ID_DOI_TAC, TEN, DIA_CHI, PHUONG_ID, DANH_GIA) VALUES (12, 1, 'River Palm Resort', '23 An Dương Vương', 5, 4);
INSERT INTO KHU_NGHI_DUONG (ID, ID_DOI_TAC, TEN, DIA_CHI, PHUONG_ID, DANH_GIA) VALUES (13, 1, 'Mystic Lagoon Resort', '47 Nguyễn Biểu', 6, 5);
INSERT INTO KHU_NGHI_DUONG (ID, ID_DOI_TAC, TEN, DIA_CHI, PHUONG_ID, DANH_GIA) VALUES (14, 1, 'Tropical Garden Resort', '9 Lý Quang Sung', 6, 4);
INSERT INTO KHU_NGHI_DUONG (ID, ID_DOI_TAC, TEN, DIA_CHI, PHUONG_ID, DANH_GIA) VALUES (15, 1, 'Island View Resort', '7 Hải Thượng Lãn Ông', 5, 5);

-- Insert Hình ảnh cho mỗi Resort
INSERT INTO HINH_KHU_NGHI_DUONG (ID, ID_KHU_NGHI_DUONG, URL) VALUES (1, 1, 'https://previews.123rf.com/images/klavapuk/klavapuk1008/klavapuk100800017/7603520-icon-of-resort-hotel.jpg');
INSERT INTO HINH_KHU_NGHI_DUONG (ID, ID_KHU_NGHI_DUONG, URL) VALUES (2, 2, 'https://previews.123rf.com/images/klavapuk/klavapuk1008/klavapuk100800017/7603520-icon-of-resort-hotel.jpg');
INSERT INTO HINH_KHU_NGHI_DUONG (ID, ID_KHU_NGHI_DUONG, URL) VALUES (3, 3, 'https://previews.123rf.com/images/klavapuk/klavapuk1008/klavapuk100800017/7603520-icon-of-resort-hotel.jpg');
INSERT INTO HINH_KHU_NGHI_DUONG (ID, ID_KHU_NGHI_DUONG, URL) VALUES (4, 4, 'https://previews.123rf.com/images/klavapuk/klavapuk1008/klavapuk100800017/7603520-icon-of-resort-hotel.jpg');
INSERT INTO HINH_KHU_NGHI_DUONG (ID, ID_KHU_NGHI_DUONG, URL) VALUES (5, 5, 'https://previews.123rf.com/images/klavapuk/klavapuk1008/klavapuk100800017/7603520-icon-of-resort-hotel.jpg');
INSERT INTO HINH_KHU_NGHI_DUONG (ID, ID_KHU_NGHI_DUONG, URL) VALUES (6, 6, 'https://previews.123rf.com/images/klavapuk/klavapuk1008/klavapuk100800017/7603520-icon-of-resort-hotel.jpg');
INSERT INTO HINH_KHU_NGHI_DUONG (ID, ID_KHU_NGHI_DUONG, URL) VALUES (7, 7, 'https://previews.123rf.com/images/klavapuk/klavapuk1008/klavapuk100800017/7603520-icon-of-resort-hotel.jpg');
INSERT INTO HINH_KHU_NGHI_DUONG (ID, ID_KHU_NGHI_DUONG, URL) VALUES (8, 8, 'https://previews.123rf.com/images/klavapuk/klavapuk1008/klavapuk100800017/7603520-icon-of-resort-hotel.jpg');
INSERT INTO HINH_KHU_NGHI_DUONG (ID, ID_KHU_NGHI_DUONG, URL) VALUES (9, 9, 'https://previews.123rf.com/images/klavapuk/klavapuk1008/klavapuk100800017/7603520-icon-of-resort-hotel.jpg');
INSERT INTO HINH_KHU_NGHI_DUONG (ID, ID_KHU_NGHI_DUONG, URL) VALUES (10, 10, 'https://previews.123rf.com/images/klavapuk/klavapuk1008/klavapuk100800017/7603520-icon-of-resort-hotel.jpg');
INSERT INTO HINH_KHU_NGHI_DUONG (ID, ID_KHU_NGHI_DUONG, URL) VALUES (11, 11, 'https://previews.123rf.com/images/klavapuk/klavapuk1008/klavapuk100800017/7603520-icon-of-resort-hotel.jpg');
INSERT INTO HINH_KHU_NGHI_DUONG (ID, ID_KHU_NGHI_DUONG, URL) VALUES (12, 12, 'https://previews.123rf.com/images/klavapuk/klavapuk1008/klavapuk100800017/7603520-icon-of-resort-hotel.jpg');
INSERT INTO HINH_KHU_NGHI_DUONG (ID, ID_KHU_NGHI_DUONG, URL) VALUES (13, 13, 'https://previews.123rf.com/images/klavapuk/klavapuk1008/klavapuk100800017/7603520-icon-of-resort-hotel.jpg');
INSERT INTO HINH_KHU_NGHI_DUONG (ID, ID_KHU_NGHI_DUONG, URL) VALUES (14, 14, 'https://previews.123rf.com/images/klavapuk/klavapuk1008/klavapuk100800017/7603520-icon-of-resort-hotel.jpg');
INSERT INTO HINH_KHU_NGHI_DUONG (ID, ID_KHU_NGHI_DUONG, URL) VALUES (15, 15, 'https://previews.123rf.com/images/klavapuk/klavapuk1008/klavapuk100800017/7603520-icon-of-resort-hotel.jpg');

--LOAI_PHONG
-- Resort 1
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (1, 'Deluxe Room', 30, '1-2 người', 'Tiêu chuẩn 1', 2, 2, 500000);
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (1, 'Premium Room', 40, '2-3 người', 'Tiêu chuẩn 2', 2, 3, 700000);

-- Resort 2
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (2, 'Garden View Room', 35, '2 người', 'Tiêu chuẩn 1', 2, 2, 600000);
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (2, 'Sea View Room', 50, '3 người', 'Tiêu chuẩn 2', 2, 3, 900000);

-- Resort 3
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (3, 'Mountain View Room', 45, '2 người', 'Tiêu chuẩn 1', 2, 2, 650000);
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (3, 'Forest View Room', 55, '3 người', 'Tiêu chuẩn 2', 2, 3, 800000);

-- Resort 4
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (4, 'Beachfront Room', 40, '2 người', 'Tiêu chuẩn 1', 2, 2, 750000);
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (4, 'Ocean View Room', 50, '3 người', 'Tiêu chuẩn 2', 2, 3, 1000000);

-- Resort 5
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (5, 'Luxury Suite', 60, '3 người', 'Tiêu chuẩn 1', 2, 3, 1200000);
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (5, 'Honeymoon Suite', 70, '3-4 người', 'Tiêu chuẩn 2', 2, 4, 1500000);

-- Resort 6
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (6, 'Poolside Room', 35, '2 người', 'Tiêu chuẩn 1', 2, 2, 550000);
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (6, 'Sunset Room', 45, '3 người', 'Tiêu chuẩn 2', 2, 3, 750000);

-- Resort 7
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (7, 'Jungle Room', 50, '2 người', 'Tiêu chuẩn 1', 2, 2, 700000);
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (7, 'Cliffside Room', 60, '3 người', 'Tiêu chuẩn 2', 2, 3, 850000);

-- Resort 8
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (8, 'Lagoon Room', 40, '2 người', 'Tiêu chuẩn 1', 2, 2, 650000);
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (8, 'Island View Room', 55, '3 người', 'Tiêu chuẩn 2', 2, 3, 900000);

-- Resort 9
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (9, 'City View Room', 35, '2 người', 'Tiêu chuẩn 1', 2, 2, 600000);
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (9, 'Mountain Retreat Room', 45, '3 người', 'Tiêu chuẩn 2', 2, 3, 750000);

-- Resort 10
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (10, 'Forest Cabin', 40, '2 người', 'Tiêu chuẩn 1', 2, 2, 650000);
INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (10, 'Lake View Room', 55, '3 người', 'Tiêu chuẩn 2', 2, 3, 800000);

--PHONG
-- Resort 1
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (1, 1, 'Available');
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (1, 2, 'Available');

-- Resort 2
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (2, 3, 'Available');
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (2, 4, 'Booked');

-- Resort 3
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (3, 5, 'Available');
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (3, 6, 'Available');

-- Resort 4
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (4, 7, 'Available');
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (4, 8, 'Booked');

-- Resort 5
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (5, 9, 'Available');
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (5, 10, 'Available');

-- Resort 6
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (6, 11, 'Booked');
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (6, 12, 'Available');

-- Resort 7
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (7, 13, 'Booked');
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (7, 14, 'Available');

-- Resort 8
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (8, 15, 'Available');
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (8, 16, 'Available');

-- Resort 9
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (9, 17, 'Booked');
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (9, 18, 'Available');

-- Resort 10
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (10, 19, 'Available');
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI)
VALUES (10, 20, 'Booked');

--GOI_DAT_PHONG
-- Resort 1
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (1, 1000000);
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (2, 1500000);

-- Resort 2
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (3, 1200000);
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (4, 1800000);

-- Resort 3
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (5, 1300000);
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (6, 1900000);

-- Resort 4
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (7, 1400000);
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (8, 2000000);

-- Resort 5
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (9, 1500000);
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (10, 2100000);

-- Resort 6
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (11, 1600000);
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (12, 2200000);

-- Resort 7
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (13, 1700000);
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (14, 2300000);

-- Resort 8
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (15, 1800000);
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (16, 2400000);

-- Resort 9
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (17, 1900000);
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (18, 2500000);

-- Resort 10
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (19, 2000000);
INSERT INTO GOI_DAT_PHONG (ID_LOAI_PHONG, TONG_GIATIEN)
VALUES (20, 2600000);

/* 1. Dịch vụ chuẩn */
INSERT INTO DICH_VU (ID, TEN_DICH_VU, MO_TA) VALUES (1, 'Buffet Breakfast','Bữa sáng buffet quốc tế (Âu & Á)');
INSERT INTO DICH_VU (ID, TEN_DICH_VU, MO_TA) VALUES (2, 'Đưa đón sân bay (2 chiều)','Xe riêng đưa đón sân bay 2 chiều, tài xế đón tận sảnh đến');
INSERT INTO DICH_VU (ID, TEN_DICH_VU, MO_TA) VALUES (3, 'Gói Spa thư giãn','Liệu trình spa 60 phút thư giãn toàn thân');
INSERT INTO DICH_VU (ID, TEN_DICH_VU, MO_TA) VALUES (4, 'Gym 24h','Phòng tập đầy đủ thiết bị, mở cửa cả ngày');
INSERT INTO DICH_VU (ID, TEN_DICH_VU, MO_TA) VALUES (5, 'Kids Club','Khu vui chơi & trông trẻ chuyên nghiệp');
INSERT INTO DICH_VU (ID, TEN_DICH_VU, MO_TA) VALUES (6, 'Romantic Dinner','	B?a t?i l�ng m?n c?nh bi?n/ h? boi');
INSERT INTO DICH_VU (ID, TEN_DICH_VU, MO_TA) VALUES (7, 'Bicycle Rental','	Thu� xe d?p kh�m ph� khu ngh?');

/*----------------------------------------------------------
1. PH�N B? D?CH V? ? RESORT  (45 d�ng = 3 d?ch v?/resort)
----------------------------------------------------------*/
-- Resort 1 � Sunshine
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1 , 1,  1, 200000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (2 , 4,  1, 100000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (3 , 6,  1, 800000);

-- Resort 2 � Emerald Bay
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (4 , 1,  2, 200000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (5 , 2,  2, 300000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (6 , 5,  2, 150000);

-- Resort 3 � Golden Sands
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (7 , 3,  3, 700000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (8 , 4,  3, 100000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (9 , 7,  3,  70000);

-- Resort 4 � Green Valley
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (10, 1,  4, 200000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (11, 5,  4, 150000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (12, 6,  4, 800000);

-- Resort 5 � White Pearl
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (13, 2,  5, 300000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (14, 3,  5, 700000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (15, 6,  5, 800000);

-- Resort 6 � Ocean Breeze
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (16, 1,  6, 200000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (17, 4,  6, 100000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (18, 5,  6, 150000);

-- Resort 7 � Blue Sky
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (19, 2,  7, 300000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (20, 4,  7, 100000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (21, 7,  7,  70000);

-- Resort 8 � Ruby Island
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (22, 1,  8, 200000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (23, 3,  8, 700000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (24, 5,  8, 150000);

-- Resort 9 � White Lotus
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (25, 2,  9, 300000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (26, 3,  9, 700000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (27, 6,  9, 800000);

-- Resort 10 � Silver Sea
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (28, 1, 10, 200000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (29, 4, 10, 100000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (30, 7, 10,  70000);

-- Resort 11 � Diamond Shore
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (31, 3, 11, 700000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (32, 5, 11, 150000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (33, 6, 11, 800000);

-- Resort 12 � River Palm
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (34, 1, 12, 200000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (35, 2, 12, 300000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (36, 7, 12,  70000);

-- Resort 13 � Mystic Lagoon
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (37, 2, 13, 300000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (38, 5, 13, 150000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (39, 6, 13, 800000);

-- Resort 14 � Tropical Garden
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (40, 3, 14, 700000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (41, 4, 14, 100000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (42, 5, 14, 150000);

-- Resort 15 � Island View
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (43, 1, 15, 200000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (44, 3, 15, 700000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (45, 7, 15,  70000);

/*----------------------------------------------------------
2. D?CH V? M?C �?NH ? G�I �?T PH�NG  (20 g�i d?u ti�n)
   � M?i resort (1-10) c� 2 g�i; ch?n 2 d?ch v? d?u
----------------------------------------------------------*/
-- Resort 1 ? G�i 1 v� 2
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1 ,  1, 0);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (2 ,  2, 0);

-- Resort 2 ? G�i 3 v� 4
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (4 ,  3, 0);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (5 ,  4, 0);

-- Resort 3 ? G�i 5 v� 6
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (7 ,  5, 0);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (8 ,  6, 0);

-- Resort 4 ? G�i 7 v� 8
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (10,  7, 0);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (11,  8, 0);

-- Resort 5 ? G�i 9 v� 10
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (13,  9, 0);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (14, 10, 0);

-- Resort 6 ? G�i 11 v� 12
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (16, 11, 0);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (17, 12, 0);

-- Resort 7 ? G�i 13 v� 14
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (19, 13, 0);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (20, 14, 0);

-- Resort 8 ? G�i 15 v� 16
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (22, 15, 0);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (23, 16, 0);

-- Resort 9 ? G�i 17 v� 18
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (25, 17, 0);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (26, 18, 0);

-- Resort 10 ? G�i 19 v� 20
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (28, 19, 0);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (29, 20, 0);

--INSERT H�NH ?NH, TI?N �CH
INSERT INTO TIEN_ICH (ID, LOAI_TIEN_ICH, ICON_URL) VALUES(1, 'Wifi mi?n ph�', 'https://cdn-icons-png.flaticon.com/512/1074/1074034.png');
INSERT INTO TIEN_ICH (ID, LOAI_TIEN_ICH, ICON_URL) VALUES(2, 'B?n t?m', 'https://cdn-icons-png.flaticon.com/512/6364/6364746.png');
INSERT INTO TIEN_ICH (ID, LOAI_TIEN_ICH, ICON_URL) VALUES(3, '�i?u h�a', 'https://cdn-icons-png.flaticon.com/512/2784/2784364.png');
INSERT INTO TIEN_ICH (ID, LOAI_TIEN_ICH, ICON_URL) VALUES(4, 'Tivi', 'https://cdn-icons-png.flaticon.com/512/942/942100.png');
INSERT INTO TIEN_ICH (ID, LOAI_TIEN_ICH, ICON_URL) VALUES(5, 'M�y s?y t�c', 'https://cdn-icons-png.flaticon.com/512/970/97020.png');
INSERT INTO TIEN_ICH (ID, LOAI_TIEN_ICH, ICON_URL) VALUES(6, 'Ban c�ng', 'https://cdn-icons-png.flaticon.com/512/7028/7028359.png');
INSERT INTO TIEN_ICH (ID, LOAI_TIEN_ICH, ICON_URL) VALUES(7, 'T? l?nh', 'https://cdn-icons-png.flaticon.com/512/4409/4409132.png');
INSERT INTO TIEN_ICH (ID, LOAI_TIEN_ICH, ICON_URL) VALUES(8, 'M�y pha c� ph�', 'https://cdn-icons-png.flaticon.com/512/1412/14125.png');
INSERT INTO TIEN_ICH (ID, LOAI_TIEN_ICH, ICON_URL) VALUES(9, 'Gh? Sofa', 'https://cdn-icons-png.flaticon.com/512/2331/2331797.png');
INSERT INTO TIEN_ICH (ID, LOAI_TIEN_ICH, ICON_URL) VALUES(10, 'B�n l�m vi?c', 'https://cdn-icons-png.flaticon.com/512/5600/5600691.png');
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1, 1, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (2, 1, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (3, 1, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (4, 2, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (5, 2, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (6, 2, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (7, 3, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (8, 3, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (9, 3, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (10, 4, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (11, 4, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (12, 4, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (13, 5, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (14, 5, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (15, 5, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (16, 6, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (17, 6, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (18, 6, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (19, 7, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (20, 7, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (21, 7, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (22, 8, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (23, 8, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (24, 8, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (25, 9, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (26, 9, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (27, 9, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (28, 10, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (29, 10, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (30, 10, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (31, 11, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (32, 11, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (33, 11, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (34, 12, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (35, 12, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (36, 12, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (37, 13, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (38, 13, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (39, 13, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (40, 14, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (41, 14, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (42, 14, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (43, 15, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (44, 15, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (45, 15, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (46, 16, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (47, 16, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (48, 16, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (49, 17, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (50, 17, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (51, 17, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (52, 18, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (53, 18, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (54, 18, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (55, 19, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (56, 19, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (57, 19, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (58, 20, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (59, 20, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (60, 20, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (1, 2);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (1, 3);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (1, 4);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (2, 3);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (2, 5);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (2, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (3, 4);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (3, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (3, 10);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (4, 3);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (4, 5);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (4, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (5, 1);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (5, 6);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (6, 3);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (6, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (6, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (7, 2);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (7, 5);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (7, 8);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (8, 5);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (8, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (8, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (9, 8);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (9, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (9, 10);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (10, 1);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (11, 2);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (11, 3);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (11, 4);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (12, 3);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (12, 5);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (12, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (13, 4);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (13, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (13, 10);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (14, 3);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (14, 5);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (14, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (15, 1);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (15, 6);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (16, 3);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (16, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (16, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (17, 2);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (17, 5);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (17, 8);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (18, 5);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (18, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (18, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (19, 8);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (19, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (19, 10);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (20, 1);

--PHONG TR?N RESORT
INSERT INTO KHU_NGHI_DUONG (ID, ID_DOI_TAC, TEN, DIA_CHI, PHUONG_ID, DANH_GIA) VALUES (16, 1, 'Phong Ch?n Resort', '123 �u?ng Bi?n, TP.HCM', 1, 5);
INSERT INTO LOAI_PHONG (ID, ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA) VALUES (200, 16, 'Ph�ng 2 ngu?i', 25, '2 ngu?i', 'Ti�u chu?n 1', 1, 2, 600000);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1000, 200, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1001, 200, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1002, 200, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (200, 1);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (200, 2);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (200, 3);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (200, 4);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (200, 5);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (200, 6);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (200, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (200, 8);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (200, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (200, 10);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3000, 200, 891419);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3001, 200, 772975);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3002, 200, 976828);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3003, 200, 791993);

INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6000, 16, 200, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7000, 6000, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6001,16, 200, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7001, 6001, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6002,16, 200, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7002, 6002, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6003,16, 200, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7003, 6003, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO LOAI_PHONG (ID, ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA) VALUES (201, 16, 'Ph�ng 2 ngu?i', 30, '2 ngu?i', 'Ti�u chu?n 2', 1, 2, 600000);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1003, 201, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1004, 201, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1005, 201, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (201, 1);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (201, 2);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (201, 3);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (201, 4);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (201, 5);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (201, 6);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (201, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (201, 8);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (201, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (201, 10);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3004, 201, 787815);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3005, 201, 738833);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3006, 201, 752975);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3007, 201, 879575);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6004,16, 201, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7004, 6004, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6005,16, 201, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7005, 6005, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6006,16, 201, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7006, 6006, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6007,16, 201, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7007, 6007, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO LOAI_PHONG (ID, ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA) VALUES (202, 16, 'Ph�ng 4 ngu?i', 35, '4 ngu?i', 'Ti�u chu?n 3', 2, 4, 1200000);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1006, 202, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1007, 202, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1008, 202, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (202, 1);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (202, 2);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (202, 3);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (202, 4);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (202, 5);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (202, 6);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (202, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (202, 8);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (202, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (202, 10);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3008, 202, 1407681);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3009, 202, 1875772);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3010, 202, 1801680);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3011, 202, 1275224);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6008,16, 202, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7008, 6008, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6009,16, 202, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7009, 6009, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6010,16, 202, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7010, 6010, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6011,16, 202, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7011, 6011, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO LOAI_PHONG (ID, ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA) VALUES (203, 16, 'Ph�ng 6 ngu?i', 40, '6 ngu?i', 'Ti�u chu?n 4', 3, 6, 1800000);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1009, 203, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1010, 203, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1011, 203, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (203, 1);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (203, 2);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (203, 3);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (203, 4);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (203, 5);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (203, 6);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (203, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (203, 8);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (203, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (203, 10);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3012, 203, 2348405);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3013, 203, 2343339);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6012,16, 203, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7012, 6012, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6013,16, 203, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7013, 6013, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO LOAI_PHONG (ID, ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA) VALUES (204, 16, 'Ph�ng 8 ngu?i', 45, '8 ngu?i', 'Ti�u chu?n 5', 4, 8, 2400000);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1012, 204, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1013, 204, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1014, 204, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (204, 1);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (204, 2);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (204, 3);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (204, 4);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (204, 5);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (204, 6);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (204, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (204, 8);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (204, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (204, 10);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3014, 204, 2694550);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3015, 204, 3069714);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3016, 204, 2740306);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3017, 204, 2787196);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6014,16, 204, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7014, 6014, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6015,16, 204, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7015, 6015, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6016,16, 204, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7016, 6016, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6017,16, 204, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7017, 6017, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO LOAI_PHONG (ID, ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA) VALUES (205, 16, 'Ph�ng 12 ngu?i', 50, '12 ngu?i', 'Ti�u chu?n 6', 6, 12, 3600000);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1015, 205, 'https://www.lanha.vn/wp-content/uploads/2023/07/thiet-ke-noi-that-phong-ngu-bs5.jpeg.webp', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1016, 205, 'https://noithatlacgia.com/wp-content/uploads/2022/10/thiet-ke-noi-that-biet-thu-sang-trong-anh-thuan-hai-duong-7.jpg', 0);
INSERT INTO HINH_PHONG (ID, ID_LOAI_PHONG, URL, IS_DELETED) VALUES (1017, 205, 'https://aeros.vn/upload/images/menu_page/aeros-thiet-ke-phong-ngu-06.webp', 0);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (205, 1);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (205, 2);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (205, 3);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (205, 4);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (205, 5);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (205, 6);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (205, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (205, 8);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (205, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (205, 10);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3018, 205, 3951448);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3019, 205, 5702689);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3020, 205, 5456751);
INSERT INTO GOI_DAT_PHONG (ID, ID_LOAI_PHONG, TONG_GIATIEN) VALUES (3021, 205, 5678538);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6018,16, 205, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7018, 6018, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6019,16, 205, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7019, 6019, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6020,16, 205, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7020, 6020, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO PHONG (ID,ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, TRANG_THAI) VALUES (6021,16, 205, 'Available');
INSERT INTO THOIGIAN_PHONG_BAN (ID, ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG) VALUES (7021, 6021, TO_TIMESTAMP('2025-05-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);

INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1001, 3, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1001, 3000, 50000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1002, 2, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1002, 3001, 50000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1003, 4, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1003, 3001, 50000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1004, 4, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1004, 3002, 50000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1005, 7, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1005, 3003, 50000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1006, 2, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1006, 3004, 50000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1007, 5, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1007, 3004, 50000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1008, 5, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1008, 3005, 50000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1009, 2, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1009, 3006, 50000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1010, 1, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1010, 3007, 0);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1011, 7, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1011, 3007, 50000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1012, 6, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1012, 3008, 0);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1013, 5, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1013, 3009, 0);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1014, 6, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1014, 3010, 0);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1015, 7, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1015, 3011, 0);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1016, 4, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1016, 3011, 0);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1017, 2, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1017, 3012, 50000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1018, 2, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1018, 3013, 0);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1019, 1, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1019, 3013, 50000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1020, 2, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1020, 3014, 0);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1021, 7, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1021, 3015, 50000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1022, 3, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1022, 3016, 0);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1023, 4, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1023, 3017, 0);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1024, 2, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1024, 3018, 50000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1025, 4, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1025, 3018, 50000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1026, 4, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1026, 3019, 50000);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1027, 1, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1027, 3020, 0);
INSERT INTO DICH_VU_KHU_NGHI_DUONG (ID, ID_DICH_VU, ID_RESORT, GIA) VALUES (1028, 4, 16, 100000);
INSERT INTO DICH_VU_MAC_DINH (ID_DICH_VU_KHU_NGHI_DUONG, ID_GOI_DAT_PHONG, GIAMGIA) VALUES (1028, 3021, 50000);

DELETE FROM TIEN_ICH_PHONG WHERE ID_PHONG BETWEEN 200 AND 205;
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (200, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (200, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (200, 2);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (200, 8);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (201, 6);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (201, 8);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (201, 3);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (202, 4);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (202, 10);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (202, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (203, 3);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (203, 4);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (203, 5);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (204, 4);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (204, 1);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (204, 8);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (204, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (205, 9);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (205, 6);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (205, 7);
INSERT INTO TIEN_ICH_PHONG (ID_PHONG, ID_TIEN_ICH) VALUES (205, 2);

--INSERT ��NH GI� CHO RESORT 1
INSERT INTO DANH_GIA (ID, ID_KHU_NGHI_DUONG, ID_KHACH_HANG, DIEM, NOI_DUNG, THOIGIAN_TAO)
VALUES (1, 1, 1, 5, 'Resort r?t d?p, d?ch v? tuy?t v?i.', TO_DATE('2024-07-15', 'YYYY-MM-DD'));

INSERT INTO DANH_GIA (ID, ID_KHU_NGHI_DUONG, ID_KHACH_HANG, DIEM, NOI_DUNG, THOIGIAN_TAO)
VALUES (2, 1, 1, 4, 'Ph�ng s?ch s?, nh�n vi�n th�n thi?n.', TO_DATE('2024-08-20', 'YYYY-MM-DD'));

INSERT INTO DANH_GIA (ID, ID_KHU_NGHI_DUONG, ID_KHACH_HANG, DIEM, NOI_DUNG, THOIGIAN_TAO)
VALUES (3, 1, 1, 3, 'C?nh d?p nhung an u?ng chua ngon.', TO_DATE('2024-09-05', 'YYYY-MM-DD'));
INSERT INTO DANH_GIA (ID, ID_KHU_NGHI_DUONG, ID_KHACH_HANG, DIEM, NOI_DUNG, THOIGIAN_TAO)
VALUES (4, 1, 1, 5, 'Tr?i nghi?m d�ng nh?, s? quay l?i.', TO_DATE('2024-10-01', 'YYYY-MM-DD'));
INSERT INTO DANH_GIA (ID, ID_KHU_NGHI_DUONG, ID_KHACH_HANG, DIEM, NOI_DUNG, THOIGIAN_TAO)
VALUES (5, 1, 1, 2, 'Kh� ?n �o, chua d�ng mong d?i.', TO_DATE('2024-11-11', 'YYYY-MM-DD'));
INSERT INTO DANH_GIA (ID, ID_KHU_NGHI_DUONG, ID_KHACH_HANG, DIEM, NOI_DUNG, THOIGIAN_TAO)
VALUES (6, 1, 1, 4, 'View d?p, c� h? boi s?ch.', TO_DATE('2025-01-05', 'YYYY-MM-DD'));
INSERT INTO DANH_GIA (ID, ID_KHU_NGHI_DUONG, ID_KHACH_HANG, DIEM, NOI_DUNG, THOIGIAN_TAO)
VALUES (7, 1, 1, 5, 'D?ch v? r?t chu d�o, h�i l�ng.', TO_DATE('2025-01-22', 'YYYY-MM-DD'));
INSERT INTO DANH_GIA (ID, ID_KHU_NGHI_DUONG, ID_KHACH_HANG, DIEM, NOI_DUNG, THOIGIAN_TAO)
VALUES (8, 1, 1, 3, 'Gi� hoi cao so v?i ch?t lu?ng.', TO_DATE('2025-02-10', 'YYYY-MM-DD'));
INSERT INTO DANH_GIA (ID, ID_KHU_NGHI_DUONG, ID_KHACH_HANG, DIEM, NOI_DUNG, THOIGIAN_TAO)
VALUES (9, 1, 1, 4, 'Khu�n vi�n r?ng, th�ch h?p gia d�nh.', TO_DATE('2025-03-01', 'YYYY-MM-DD'));
INSERT INTO DANH_GIA (ID, ID_KHU_NGHI_DUONG, ID_KHACH_HANG, DIEM, NOI_DUNG, THOIGIAN_TAO)
VALUES (10, 1, 1, 5, 'Tuy?t v?i, kh�ng c� g� d? ch�.', TO_DATE('2025-03-28', 'YYYY-MM-DD'));

-----DATA TEST DAT_PHONG, CHI_TIET_DAT_PHONG
-- Th�m m?t don d?t ph�ng m?i v?i tr?ng th�i "Pending" (gi? h�ng)
INSERT INTO DAT_PHONG (ID, ID_KHACH_HANG, THOI_GIAN_TAO, TRANG_THAI, TONG_GIATIEN, TAIKHOAN_NGANHANG, TEN_TKNH, TEN_NGANHANG)
VALUES (100, 1, CURRENT_TIMESTAMP, 'Pending', 0, '9876543210', 'Nguy?n Van A', 'Vietcombank');

-- Th�m m?t don d?t ph�ng d� ho�n th�nh d? so s�nh
INSERT INTO DAT_PHONG (ID, ID_KHACH_HANG, THOI_GIAN_TAO, TRANG_THAI, TONG_GIATIEN, TAIKHOAN_NGANHANG, TEN_TKNH, TEN_NGANHANG)
VALUES (101, 1, CURRENT_TIMESTAMP, 'Confirmed', 3500000, '9876543210', 'Nguy?n Van A', 'Vietcombank');

-- TH�M �?I GI?M GI�
INSERT INTO GIAMGIA (ID,ID_LOAI_PHONG, LOAI_GIAMGIA, GIA_TRI, MUC_TOI_DA, NGAY_BAT_DAU, NGAY_KET_THUC, TRANG_THAI, TEN_GIAMGIA)
VALUES(1, 1, 'Ph?n tram', 10, 200000, TO_DATE('2025-05-01', 'YYYY-MM-DD'), TO_DATE('2025-05-31', 'YYYY-MM-DD'), '�ang �p d?ng', 'Gi�m gi� 10%');

-- Th�m c�c chi ti?t d?t ph�ng v�o gi? h�ng (don h�ng Pending)
INSERT INTO CHI_TIET_DAT_PHONG (ID, ID_DAT_PHONG, ID_GOI_DAT_PHONG, ID_GIAMGIA, SO_LUONG_PHONG, SO_LUONG_DICH_VU_YEU_CAU, TONG_GIATIEN, NGAY_BAT_DAU, NGAY_KET_THUC, TRANG_THAI)
VALUES (1, 100, 1, 1, 2, 1, 1200000, TO_TIMESTAMP('2025-06-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-06-03 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Pending');

INSERT INTO CHI_TIET_DAT_PHONG (ID, ID_DAT_PHONG, ID_GOI_DAT_PHONG, ID_GIAMGIA, SO_LUONG_PHONG, SO_LUONG_DICH_VU_YEU_CAU, TONG_GIATIEN, NGAY_BAT_DAU, NGAY_KET_THUC, TRANG_THAI)
VALUES (2, 100, 2, 1, 1, 2, 800000, TO_TIMESTAMP('2025-06-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-06-03 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Pending');

--INSERT �? TEST T�NH NANG XEM L?CH S? �?T PH�NG

INSERT INTO DAT_PHONG (ID_KHACH_HANG, THOI_GIAN_TAO, TRANG_THAI, TONG_GIATIEN, TAIKHOAN_NGANHANG, TEN_TKNH, TEN_NGANHANG)
VALUES (1, CURRENT_TIMESTAMP, '�� thanh to�n', 5000000.00, '123456789', 'zalopay', 'ZaloPay');


INSERT INTO DAT_PHONG (ID_KHACH_HANG, THOI_GIAN_TAO, TRANG_THAI, TONG_GIATIEN, TAIKHOAN_NGANHANG, TEN_TKNH, TEN_NGANHANG)
VALUES (1, CURRENT_TIMESTAMP, '�� thanh to�n', 250000.00, '257329', 'zalopay', 'ZaloPay');

-- 2. Ch? (Pending - gi? h�ng)
INSERT INTO DAT_PHONG (ID_KHACH_HANG, THOI_GIAN_TAO, TRANG_THAI, TONG_GIATIEN, TAIKHOAN_NGANHANG, TEN_TKNH, TEN_NGANHANG)
VALUES (1, CURRENT_TIMESTAMP, 'Pending', 3500000.00, NULL, NULL, NULL);

-- 1. �� thanh to�n + Completed (ng�y d� qua)
INSERT INTO CHI_TIET_DAT_PHONG (ID_DAT_PHONG, ID_GOI_DAT_PHONG, SO_LUONG_PHONG, SO_LUONG_DICH_VU_YEU_CAU, TONG_GIATIEN, NGAY_BAT_DAU, NGAY_KET_THUC, TRANG_THAI, ID_GIAMGIA)
VALUES (1, 1, 1, 2, 2500000.00, TO_TIMESTAMP('2023-10-15 14:00:00','YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-10-20 12:00:00','YYYY-MM-DD HH24:MI:SS'), '�� thanh to�n', 1);
-- �� h?y
INSERT INTO CHI_TIET_DAT_PHONG (ID_DAT_PHONG, ID_GOI_DAT_PHONG, SO_LUONG_PHONG, SO_LUONG_DICH_VU_YEU_CAU, TONG_GIATIEN, NGAY_BAT_DAU, NGAY_KET_THUC, TRANG_THAI, ID_GIAMGIA)
VALUES (1, 2, 1, 1, 1500000.00,  TO_TIMESTAMP('2023-11-10 14:00:00','YYYY-MM-DD HH24:MI:SS'),  TO_TIMESTAMP('2023-11-15 12:00:00','YYYY-MM-DD HH24:MI:SS'), '�� h?y', 1);
--Upcoming
INSERT INTO CHI_TIET_DAT_PHONG (ID_DAT_PHONG, ID_GOI_DAT_PHONG, SO_LUONG_PHONG, SO_LUONG_DICH_VU_YEU_CAU, TONG_GIATIEN, NGAY_BAT_DAU, NGAY_KET_THUC, TRANG_THAI, ID_GIAMGIA)
VALUES (1, 3, 2, 3, 3000000.00, TO_TIMESTAMP('2026-11-10 14:00:00','YYYY-MM-DD HH24:MI:SS'),  TO_TIMESTAMP('2026-11-15 12:00:00','YYYY-MM-DD HH24:MI:SS'), '�� thanh to�n', 1);

-- 4. Pending (trong gi? h�ng)
INSERT INTO CHI_TIET_DAT_PHONG (ID_DAT_PHONG, ID_GOI_DAT_PHONG, SO_LUONG_PHONG, SO_LUONG_DICH_VU_YEU_CAU, TONG_GIATIEN, NGAY_BAT_DAU, NGAY_KET_THUC, TRANG_THAI, ID_GIAMGIA)
VALUES (2, 4, 1, 2, 3500000.00, TO_TIMESTAMP('2026-11-10 14:00:00','YYYY-MM-DD HH24:MI:SS'),  TO_TIMESTAMP('2026-11-15 12:00:00','YYYY-MM-DD HH24:MI:SS'), 'Pending', 1);


-- Insert m� gi?m gi� cho c�c lo?i ph�ng
-- Tham s?: ID_LOAI_PHONG, LOAI_GIAMGIA, GIA_TRI, MUC_TOI_DA, NGAY_BAT_DAU, NGAY_KET_THUC, TRANG_THAI
INSERT INTO GIAMGIA (ID, ID_LOAI_PHONG, LOAI_GIAMGIA, GIA_TRI, MUC_TOI_DA, NGAY_BAT_DAU, NGAY_KET_THUC, TRANG_THAI, TEN_GIAMGIA)
VALUES (2, 2, 'FIXED', 100000, NULL, TO_DATE('01/05/2023', 'DD/MM/YYYY'), TO_DATE('31/12/2023', 'DD/MM/YYYY'), 'ACTIVE', 'Giảm giá 1');

INSERT INTO GIAMGIA (ID, ID_LOAI_PHONG, LOAI_GIAMGIA, GIA_TRI, MUC_TOI_DA, NGAY_BAT_DAU, NGAY_KET_THUC, TRANG_THAI, TEN_GIAMGIA)
VALUES (3, 3, 'PERCENT', 15, 300000, TO_DATE('01/05/2023', 'DD/MM/YYYY'), TO_DATE('31/12/2023', 'DD/MM/YYYY'), 'ACTIVE', 'Giảm giá 2');

INSERT INTO GIAMGIA (ID, ID_LOAI_PHONG, LOAI_GIAMGIA, GIA_TRI, MUC_TOI_DA, NGAY_BAT_DAU, NGAY_KET_THUC, TRANG_THAI, TEN_GIAMGIA)
VALUES (4, 4, 'FIXED', 150000, NULL, TO_DATE('01/05/2023', 'DD/MM/YYYY'), TO_DATE('31/12/2023', 'DD/MM/YYYY'), 'ACTIVE', 'Giảm giá 3');

INSERT INTO GIAMGIA (ID, ID_LOAI_PHONG, LOAI_GIAMGIA, GIA_TRI, MUC_TOI_DA, NGAY_BAT_DAU, NGAY_KET_THUC, TRANG_THAI, TEN_GIAMGIA)
VALUES (5, 5, 'PERCENT', 20, 500000, TO_DATE('01/05/2023', 'DD/MM/YYYY'), TO_DATE('31/12/2023', 'DD/MM/YYYY'), 'ACTIVE', 'Giảm giá 4');


-- Insert d?i di?m tuong ?ng v?i m� gi?m gi�
-- Tham s?: ID, ID_MA_GIAM, GIA_TRI

INSERT INTO DOI_DIEM (ID, ID_MAGIAM, GIA_TRI)
VALUES (1, 1, 100);

INSERT INTO DOI_DIEM (ID, ID_MAGIAM, GIA_TRI)
VALUES (2, 2, 150);

INSERT INTO DOI_DIEM (ID, ID_MAGIAM, GIA_TRI)
VALUES (3, 3, 200);

INSERT INTO DOI_DIEM (ID, ID_MAGIAM, GIA_TRI)
VALUES (4, 4, 250);

INSERT INTO DOI_DIEM (ID, ID_MAGIAM, GIA_TRI)
VALUES (5, 5, 300);

COMMIT;

ALTER TABLE CHI_TIET_DAT_PHONG MODIFY (ID_GIAMGIA NULL);
