INSERT INTO "FUNCTION"(FUNCTION_NAME) VALUES('VIEW_ROOM_LIST');
INSERT INTO "FUNCTION"(FUNCTION_NAME) VALUES('PARTNER_VIEW');
INSERT INTO "FUNCTION"(FUNCTION_NAME) VALUES('CUSTOMER_VIEW');
INSERT INTO "FUNCTION"(FUNCTION_NAME) VALUES('ADMIN_VIEW');
COMMIT;

SELECT * FROM LOAI_PHONG lp;

INSERT INTO ROLE_GROUP(GROUP_NAME, DESCRIPTION) VALUES ('ADMIN', '');
INSERT INTO ROLE_GROUP(GROUP_NAME, DESCRIPTION) VALUES ('PARTNER', '');
INSERT INTO ROLE_GROUP(GROUP_NAME, DESCRIPTION) VALUES ('CUSTOMER', '');
COMMIT;
SELECT * FROM ROLE_GROUP rg;

INSERT INTO ROLE(FUNCTION_ID, ADD_PERM, EDIT_PERM, DELETE_PERM, DOWNLOAD_PERM, VIEW_PERM)
VALUES (1,1,1,1,1,1);
INSERT INTO ROLE(FUNCTION_ID, ADD_PERM, EDIT_PERM, DELETE_PERM, DOWNLOAD_PERM, VIEW_PERM)
VALUES (2,1,1,1,1,1);
INSERT INTO ROLE(FUNCTION_ID, ADD_PERM, EDIT_PERM, DELETE_PERM, DOWNLOAD_PERM, VIEW_PERM)
VALUES (3,1,1,1,1,1);
INSERT INTO ROLE(FUNCTION_ID, ADD_PERM, EDIT_PERM, DELETE_PERM, DOWNLOAD_PERM, VIEW_PERM)
VALUES (4,1,1,1,1,1);
COMMIT;
SELECT * FROM ROLE;

INSERT INTO NGUOI_DUNG(HO_TEN, EMAIL, SDT, CCCD)
VALUES ('Nguyen Thanh Thang', '23521427@gm.uit.edu.vn', '1234567890', '082205111175');
INSERT INTO NGUOI_DUNG(HO_TEN, EMAIL, SDT, CCCD)
VALUES ('Tran Nam Phong', '23521172@gm.uit.edu.vn', '1234567890', '123456678900');
INSERT INTO NGUOI_DUNG(HO_TEN, EMAIL, SDT, CCCD)
VALUES ('To Tran Nha Uyen', '23521765@gm.uit.edu.vn', '1234567890', '123456678900');
INSERT INTO NGUOI_DUNG(HO_TEN, EMAIL, SDT, CCCD)
VALUES ('Le Dao Anh Thu', '23521537@gm.uit.edu.vn', '1234567890', '123456678900');
COMMIT;
SELECT * FROM NGUOI_DUNG;

INSERT INTO TAI_KHOAN(USER_ID, TEN_TAI_KHOAN, MAT_KHAU)
VALUES (2, 'ThanhThang123', 'hash-pass-of-123');
INSERT INTO TAI_KHOAN(USER_ID, TEN_TAI_KHOAN, MAT_KHAU)
VALUES (3, 'NamPhong123', 'hash-pass-of-123');
INSERT INTO TAI_KHOAN(USER_ID, TEN_TAI_KHOAN, MAT_KHAU)
VALUES (4, 'NhaUyen123', 'hash-pass-of-123');
INSERT INTO TAI_KHOAN(USER_ID, TEN_TAI_KHOAN, MAT_KHAU)
VALUES (5, 'AnhThu123', 'hash-pass-of-123');
COMMIT;
SELECT * FROM TAI_KHOAN;

INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (1,1);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (1,2);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (1,3);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (2,1);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (2,2);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (2,3);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (3,1);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (3,2);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (3,3);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (4,1);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (4,2);
INSERT INTO ACCOUNT_ROLE_GROUP(ACCOUNT_ID, ROLE_GROUP_ID) VALUES (4,3);
COMMIT;
SELECT * FROM ACCOUNT_ROLE_GROUP;

INSERT INTO ASSIGN_ROLE_GROUP(ROLE_GROUP_ID, ROLE_ID) VALUES (1,4);
INSERT INTO ASSIGN_ROLE_GROUP(ROLE_GROUP_ID, ROLE_ID) VALUES (2,3);
INSERT INTO ASSIGN_ROLE_GROUP(ROLE_GROUP_ID, ROLE_ID) VALUES (3,2);
COMMIT;
SELECT * FROM ASSIGN_ROLE_GROUP arg;

INSERT INTO ACCOUNT_ASSIGN_ROLE(ACCOUNT_ID,ROLE_ID) VALUES(2,1);
COMMIT;
SELECT * FROM ACCOUNT_ASSIGN_ROLE;


 UPDATE TAI_KHOAN
 SET MAT_KHAU = 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3'
 WHERE MAT_KHAU = 'hash-pass-of-123';

SELECT * FROM TAI_KHOAN tk;
COMMIT;

SELECT * FROM ACCOUNT_ROLE_GROUP arg;


SELECT * FROM THANH_PHO tp;
INSERT INTO THANH_PHO (TEN_THANH_PHO) VALUES ('Hồ Chí Minh');
INSERT INTO THANH_PHO (TEN_THANH_PHO) VALUES ('Hà Nội');
INSERT INTO THANH_PHO (TEN_THANH_PHO) VALUES ('Lâm Đồng');
INSERT INTO THANH_PHO (TEN_THANH_PHO) VALUES ('Bà Rịa - Vũng Tàu');
COMMIT;

INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (1,'Quận 1');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (1,'Quận 2');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (1,'Quận 3');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (1,'Quận 4');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (2,'Ba Đình');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (2,'Cầu Giấy');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (2,'Hoàn Kiếm');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (2,'Hà Đông');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (3,'Đà Lạt');
INSERT INTO QUAN(ID_THANH_PHO, TEN_QUAN) VALUES (4,'Vũng Tàu');
COMMIT;
SELECT * FROM QUAN q;


INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (1,'Bến Thành');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (1,'Cầu Ông Lãnh');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (1,'Cô Giang');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (2,'Thảo Điền');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (2,'Thủ Thiêm');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (2,'An Khánh');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (3,'Phường 1');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (3,'Phường 2');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (3,'Phường 3');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (4,'Phường 1');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (4,'Phường 2');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (4,'Phường 3');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (5,'Vĩnh Phúc');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (6,'Dịch Vọng');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (7,'Đồng Xuân');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (8,'La Khê');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (9,'Đồng Xuân');
INSERT INTO PHUONG(ID_QUAN, TEN_PHUONG) VALUES (10,'Phường 1');
COMMIT;
SELECT * FROM PHUONG;

SELECT * FROM KHU_NGHI_DUONG knd;
COMMIT;

EXEC ThemKhuNghiDuong('ThanhThang123_2025-04-02_20:23:45','Resort name 2', '23 Hoàng Văn Thụ', 'Hồ Chí Minh', 'Quận 1', 'Bến Thành');

SELECT * FROM KHU_NGHI_DUONG knd;
SELECT * FROM ACCOUNT_TOKEN at;
SELECT * FROM TAI_KHOAN tk;
INSERT INTO DOI_TAC(ID_TAI_KHOAN, DIA_CHI, TAIKHOAN_NGANHANG, TEN_TKNH, TEN_NGANHANG)
VALUES (1, 'KTX KHU A', '0348489748', 'NGUYEN THANH THANG', 'MBBANK');
COMMIT;

SELECT * FROM DOI_TAC dt;


SELECT * FROM NLS_DATABASE_PARAMETERS WHERE PARAMETER = 'NLS_CHARACTERSET';

UPDATE THANH_PHO
SET TEN_THANH_PHO = 'Ho Chi Minh'
WHERE TEN_THANH_PHO = 'Hồ Chí Minh';

UPDATE THANH_PHO
SET TEN_THANH_PHO = 'Hồ Chí Minh'
WHERE TEN_THANH_PHO = 'Ho Chi Minh';

SELECT * FROM THANH_PHO tp;

SELECT * FROM LOAI_PHONG lp;
SELECT * FROM KHU_NGHI_DUONG knd;
SELECT * FROM DOI_TAC dt;


INSERT INTO LOAI_PHONG(ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (4, 'Phòng Hạng Sang View Biển', 20.00, 'Phòng Đôi', 'Hạng sang', 1, 2, 1000000);
INSERT INTO LOAI_PHONG(ID_KHU_NGHI_DUONG, TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA)
VALUES (4, 'Phòng Hạng Sang View Phố', 20.00, 'Phòng Đôi', 'Hạng sang', 1, 2, 1000000);
COMMIT;


CREATE OR REPLACE PROCEDURE ThemLoaiPhong(
    P_ID_KHU_NGHI_DUONG NVARCHAR2,
    p_ten NVARCHAR2,
    p_dia_chi NVARCHAR2,
    p_thanh_pho NVARCHAR2,
    p_quan NVARCHAR2,
    p_phuong NVARCHAR2
) AS
    V_USERNAME NVARCHAR2(255);
    V_ID_THANH_PHO NUMBER;
    V_ID_QUAN NUMBER;
    V_ID_PHUONG NUMBER;
    V_ID_DOI_TAC NUMBER;
BEGIN
    V_USERNAME := get_username_from_token(P_TOKEN);


    SELECT DT.ID INTO V_ID_DOI_TAC
    FROM DOI_TAC dt
    JOIN TAI_KHOAN tk ON DT.ID_TAI_KHOAN = TK.ACCOUNT_ID
    WHERE TK.TEN_TAI_KHOAN = V_USERNAME;

    SELECT TP.ID INTO V_ID_THANH_PHO
    FROM THANH_PHO tp
    WHERE TP.TEN_THANH_PHO = P_THANH_PHO;

    SELECT Q.ID INTO V_ID_QUAN
    FROM QUAN q
    WHERE Q.ID_THANH_PHO = V_ID_THANH_PHO
    AND Q.TEN_QUAN = P_QUAN;

    SELECT P.ID INTO V_ID_PHUONG
    FROM PHUONG P
    WHERE P.ID_QUAN = V_ID_QUAN
    AND P.TEN_PHUONG = P_PHUONG;

    INSERT INTO LOAI_PHONG (ID_KHU_NGHI_DUONG,TEN_LOAI_PHONG, DIEN_TICH, LOAI_PHONG_THEO_SO_LUONG, LOAI_PHONG_THEO_TIEU_CHUAN, SO_GIUONG, SO_NGUOI, GIA) -- Can them khoa ngoai cua doi tac
    VALUES (V_ID_DOI_TAC,p_ten, p_dia_chi, V_ID_PHUONG);

    COMMIT;
END;
/

SELECT * FROM LOAI_PHONG lp;

SELECT * FROM HINH_PHONG hp;


CREATE OR REPLACE PROCEDURE layTienIchTheoLoaiPhong(
  P_ROOMTYPE_ID IN NUMBER
)
AS
BEGIN
  SELECT TI.ID, TI.LOAI_TIEN_ICH, TI.ICON_URL
  FROM TIEN_ICH ti
  JOIN TIEN_ICH_PHONG tip ON TI.ID = TIP.ID_TIEN_ICH
  WHERE TIP.ID_PHONG = P_ROOMTYPE_ID;
END;

SELECT * FROM TIEN_ICH ti;
INSERT INTO TIEN_ICH(LOAI_TIEN_ICH, ICON_URL)
VALUES('Máy chiếu', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.flaticon.com%2Ffree-icon%2Flocation_535239&psig=AOvVaw1n1cI66E4KAInEmJEeOp6J&ust=1744206322300000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLDcloXJyIwDFQAAAAAdAAAAABAJ');
INSERT INTO TIEN_ICH(LOAI_TIEN_ICH, ICON_URL)
VALUES('Điều hòa', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.flaticon.com%2Ffree-icon%2Flocation_535239&psig=AOvVaw1n1cI66E4KAInEmJEeOp6J&ust=1744206322300000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLDcloXJyIwDFQAAAAAdAAAAABAJ');
INSERT INTO TIEN_ICH(LOAI_TIEN_ICH, ICON_URL)
VALUES('Lò sưởi', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.flaticon.com%2Ffree-icon%2Flocation_535239&psig=AOvVaw1n1cI66E4KAInEmJEeOp6J&ust=1744206322300000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLDcloXJyIwDFQAAAAAdAAAAABAJ');
COMMIT;

SELECT * FROM TIEN_ICH_PHONG tip;
SELECT * FROM LOAI_PHONG lp;
SELECT * FROM TIEN_ICH ti;
SELECT * FROM PHONG;
INSERT INTO TIEN_ICH_PHONG(ID_PHONG, ID_TIEN_ICH) VALUES(41,2);
INSERT INTO TIEN_ICH_PHONG(ID_PHONG, ID_TIEN_ICH) VALUES(41,3);
COMMIT;

SELECT * FROM DICH_VU dv;
SELECT * FROM DICH_VU_KHU_NGHI_DUONG;

INSERT INTO DICH_VU (TEN_DICH_VU, MO_TA) VALUES ('Spa & Massage', 'Mô tả');
INSERT INTO DICH_VU (TEN_DICH_VU, MO_TA) VALUES ('Nhà hàng & Buffet', 'Mô tả');
INSERT INTO DICH_VU (TEN_DICH_VU, MO_TA) VALUES ('Thuê xe ô tô', 'Mô tả');
INSERT INTO DICH_VU (TEN_DICH_VU, MO_TA) VALUES ('Chương trình giải trí', 'Mô tả');
INSERT INTO DICH_VU (TEN_DICH_VU, MO_TA) VALUES ('Tổ chức sự kiện', 'Mô tả');
INSERT INTO DICH_VU (TEN_DICH_VU, MO_TA) VALUES ('Tour du lịch tham quan', 'Mô tả');
COMMIT;

SELECT * FROM DICH_VU;
SELECT * FROM KHU_NGHI_DUONG knd;
SELECT * FROM DICH_VU_KHU_NGHI_DUONG;
INSERT INTO DICH_VU_KHU_NGHI_DUONG(ID_RESORT, ID_DICH_VU, GIA) VALUES (4,5,2);
INSERT INTO DICH_VU_KHU_NGHI_DUONG(ID_RESORT, ID_DICH_VU, GIA) VALUES (4,2,2);
INSERT INTO DICH_VU_KHU_NGHI_DUONG(ID_RESORT, ID_DICH_VU, GIA) VALUES (4,3,2);
COMMIT;

SELECT * FROM LOAI_PHONG;
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, MA_SO, TRANG_THAI)
VALUES (4, 4, 101, 'active');
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, MA_SO, TRANG_THAI)
VALUES (4, 3, 102, 'active');
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, MA_SO, TRANG_THAI)
VALUES (4, 3, 103, 'inactive');
INSERT INTO PHONG (ID_KHU_NGHI_DUONG, ID_LOAI_PHONG, MA_SO, TRANG_THAI)
VALUES (4, 3, 104, 'active');
COMMIT;
SELECT * FROM TAI_KHOAN tk;
SELECT * FROM KHACH_HANG kh;
INSERT INTO KHACH_HANG(ID_TAI_KHOAN, DIA_CHI, DIEM_TICH_LUY)
VALUES(1,'uit',0);
INSERT INTO KHACH_HANG(ID_TAI_KHOAN, DIA_CHI, DIEM_TICH_LUY)
VALUES(2,'uit',0);
COMMIT;

INSERT INTO THOIGIAN_PHONG_BAN (ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG)
VALUES (1, TO_TIMESTAMP('2025-04-23 09:00', 'YYYY-MM-DD HH24:MI'), TO_TIMESTAMP('2025-04-23 15:00', 'YYYY-MM-DD HH24:MI'), 1);
INSERT INTO THOIGIAN_PHONG_BAN (ID_PHONG, NGAY_BAT_DAU, NGAY_KET_THUC, ID_KHACH_HANG)
VALUES (2, TO_TIMESTAMP('2025-04-24 08:00', 'YYYY-MM-DD HH24:MI'), TO_TIMESTAMP('2025-04-24 11:00', 'YYYY-MM-DD HH24:MI'), 2);
COMMIT;


INSERT INTO DANH_GIA(ID_KHU_NGHI_DUONG, ID_KHACH_HANG, DIEM, NOI_DUNG,THOIGIAN_TAO)
values(7,1,5,'Rất tốt', SYSDATE);
INSERT INTO DANH_GIA(ID_KHU_NGHI_DUONG, ID_KHACH_HANG, DIEM, NOI_DUNG, THOIGIAN_TAO)
values(7,1,4,'Chill', SYSDATE);
INSERT INTO DANH_GIA(ID_KHU_NGHI_DUONG, ID_KHACH_HANG, DIEM, NOI_DUNG, THOIGIAN_TAO)
values(7,1,2,'Chillnt', SYSDATE);
COMMIT;

INSERT INTO DAT_PHONG(ID_KHACH_HANG, THOI_GIAN_TAO, TINH_TRANG,
TONG_GIATIEN, TAIKHOAN_NGANHANG, TEN_TKNH, TEN_NGANHANG
) VALUES(1,SYSDATE, 'ĐãThanhToán', 1500000, 123456789, 'ThanhThang', 'momo');

INSERT INTO GIAMGIA(ID_LOAI_PHONG, LOAI_GIAMGIA, MUC_TOI_DA, GIA_TRI,
NGAY_BAT_DAU, NGAY_KET_THUC, TINH_TRANG)
VALUES(41,'PhầnTrăm', 1500000, 10, SYSDATE, SYSDATE, 'ĐãThanhToán');
COMMIT;


INSERT INTO  CHI_TIET_DAT_PHONG(ID_DAT_PHONG, ID_GOI_DAT_PHONG, ID_GIAMGIA,
SO_LUONG_PHONG, SO_LUONG_DICH_VU_YEU_CAU, TONG_GIATIEN,
NGAY_BAT_DAU, NGAY_KET_THUC, TINH_TRANG
)
VALUES(1,4,2, 1, 0, 1455000, SYSDATE, SYSDATE, 'ĐãThanhToán');
SELECT * FROM CHI_TIET_DAT_PHONG ctdp;


INSERT INTO HOA_DON (ID_KHACH_HANG, ID_DOI_TAC, ID_CHI_TIET_DAT_PHONG,
  TONG_GIATIEN, THOIGIAN_THANHTOAN,
  HINH_THUC_THANH_TOAN
)
VALUES (1,1,3,1455000, SYSDATE, 'momo');
SELECT * FROM HOA_DON hd;

CREATE OR REPLACE FUNCTION demHoaDonTrongNgay(
    p_id_doi_tac IN NUMBER
) RETURN NUMBER
IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM HOA_DON
    WHERE ID_DOI_TAC = p_id_doi_tac
      AND TRUNC(THOIGIAN_THANHTOAN) = TRUNC(SYSDATE); -- chỉ lấy trong ngày hiện tại

    RETURN v_count;
END;
/
SELECT demHoaDonTrongNgay(1) FROM dual;


SELECT tongHoaDonThangHienTai(1) FROM dual;

SELECT * FROM DOI_TAC dt;
UPDATE DOI_TAC
SET SO_DU = 1455000
WHERE ID = 1;

COMMIT;




SELECT KND.TEN, COUNT(DISTINCT HD.ID_CHI_TIET_DAT_PHONG)
FROM HOA_DON hd
JOIN CHI_TIET_DAT_PHONG ctdp ON HD.ID_CHI_TIET_DAT_PHONG = CTDP.ID
JOIN GOI_DAT_PHONG gdp ON CTDP.ID_GOI_DAT_PHONG = GDP.ID
JOIN LOAI_PHONG lp ON GDP.ID_LOAI_PHONG = LP.ID
JOIN KHU_NGHI_DUONG knd ON LP.ID_KHU_NGHI_DUONG = KND.ID
GROUP BY KND.TEN;

INSERT INTO LICH_SU_RUT_TIEN(ID_DOI_TAC, SOTIEN, THOIGIAN_TAO, TRANGTHAI_RUTTIEN)
VALUES (1,100000, SYSDATE, 'Chờ Duyệt');
INSERT INTO LICH_SU_RUT_TIEN(ID_DOI_TAC, SOTIEN, THOIGIAN_TAO, TRANGTHAI_RUTTIEN)
VALUES (1,50000, SYSDATE, 'Chờ Duyệt');
INSERT INTO LICH_SU_RUT_TIEN(ID_DOI_TAC, SOTIEN, THOIGIAN_TAO, TRANGTHAI_RUTTIEN)
VALUES (1,50000, SYSDATE, 'Chờ Duyệt');
COMMIT;


SELECT * FROM LICH_SU_RUT_TIEN lsrt;

UPDATE LICH_SU_RUT_TIEN
SET TRANGTHAI_RUTTIEN = 'Chờ phê duyệt'
WHERE TRANGTHAI_RUTTIEN = 'Chờ Duyệt';
COMMIT;

SELECT * FROM DAT_PHONG dp;

SELECT * FROM CHI_TIET_DAT_PHONG ctdp;

INSERT INTO DAT_PHONG(ID_KHACH_HANG, THOI_GIAN_TAO, TINH_TRANG,
TONG_GIATIEN, TAIKHOAN_NGANHANG, TEN_TKNH, TEN_NGANHANG
) VALUES(1,SYSDATE, 'Chưa thanh toán', 1230000, 123456789, 'ThanhThang', 'null');
COMMIT;

INSERT INTO  CHI_TIET_DAT_PHONG(ID_DAT_PHONG, ID_GOI_DAT_PHONG, ID_GIAMGIA,
SO_LUONG_PHONG, SO_LUONG_DICH_VU_YEU_CAU, TONG_GIATIEN,
NGAY_BAT_DAU, NGAY_KET_THUC, TINH_TRANG
)
VALUES(23,4,2, 1, 0, 1455000, SYSDATE, SYSDATE, 'Chưa thanh toán');


SELECT * FROM HOA_DON hd;
